version: "3.7"
services:
  nethermind:
    hostname: nethermind
    container_name: nethermind
    image: nethermind/nethermind:latest
    restart: always
    stop_grace_period: 1m
    networks:
      net:
        ipv4_address: 192.168.32.100
    ports:
      - "30303:30303/tcp" # p2p
      - "30303:30303/udp" # p2p
      - "8545:8545"
      - "8551:8551"
    volumes:
      - ./nethermind_db:/nethermind/nethermind_db
      - ./keystore:/nethermind/keystore
      - ./logs:/nethermind/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./xdai.cfg:/nethermind/configs/xdai.cfg
    environment:
      - NETHERMIND_CONFIG=xdai
    logging:
      driver: "local"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.32.0/24"